services:
  caddy:
    container_name: caddy
    image: caddy:2
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /pds/caddy/data
        target: /data
      - type: bind
        source: /pds/caddy/etc/caddy
        target: /etc/caddy
 
  bsky:
    image: ghcr.io/j0904/atproto:bsky-958dd9a6d0423e059a352c99e9bbb4b77da14eaa
    ports:
      - "2584:2584"
    environment:
      - BSKY_DATAPLANE_URLS=http://localhost:4000
      - BSKY_BSYNC_URL=https://bsync.bigt.ai
      - BSKY_PDS_URL=https://pds.bigt.ai
      - MOD_SERVICE_DID=did:bigt.ai:mod
      - BSKY_SERVICE_SIGNING_KEY=37a6289ce3235aac0c2eb1e4f038ee1175cef1d8d77ac5714fe98b61671d1349
      - LOG_ENABLED=true
      - BSKY_PUBLIC_URL=https://bsky.bigt.ai
      - BSKY_DISABLE_SSRF_PROTECTION="true"
# Database Configuration
      - DATABASE_URL=postgres://bsync:bsyncpass@postgres:5432/bsyncdb


  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: bsync
      POSTGRES_PASSWORD: bsyncpass
      POSTGRES_DB: bsyncdb
    ports:
      - "5432:5432"
    volumes:
      - /pds/postgres_data:/var/lib/postgresql/data

  bsync:
    image: ghcr.io/j0904/atproto:bsync-cc25cb7ceacd1d750dd0d7abb9525008170f14b9
    environment:
      BSYNC_DB_POSTGRES_URL: postgres://bsync:bsyncpass@postgres:5432/bsyncdb
      BSYNC_API_KEYS: v12I1SXs10Evh5rvMrvp5fllruvIbBtKJi//ivKtYcA=
      LOG_ENABLED: true
    depends_on:
      - postgres
    ports:
      - "2585:2585"