services:
  caddy:
    container_name: caddy
    image: caddy:2
    network_mode: host
    depends_on:
      - pds
    restart: unless-stopped
    volumes:
      - type: bind
        source: /pds/caddy/data
        target: /data
      - type: bind
        source: /pds/caddy/etc/caddy
        target: /etc/caddy

  pds:
    container_name: pds
    image: ghcr.io/bluesky-social/pds:0.4
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /pds
        target: /pds
    environment:
      PDS_HOSTNAME: pds.bigt.ai
      PDS_JWT_SECRET: db815e07fe307d8974f09b68f5541e8e
      PDS_ADMIN_PASSWORD: 9ab27af3e0a552742fe99823c4998c01
      PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: 32246d3767d771f2ea351f9c9bf2b2b28fbcbea68356fabc5c008e871e3f6ca7
      PDS_DATA_DIRECTORY: /pds
      PDS_BLOBSTORE_DISK_LOCATION: /pds/blocks
      PDS_BLOB_UPLOAD_LIMIT: 52428800
      PDS_DID_PLC_URL: https://plc.directory
      PDS_BSKY_APP_VIEW_URL: https://bsky.bigt.ai
      PDS_BSKY_APP_VIEW_DID: did:web:api.bsky.app
      PDS_REPORT_SERVICE_URL: https://mod.bsky.app
      PDS_REPORT_SERVICE_DID: did:plc:ar7c4by46qjdydhdevvrndac
      PDS_CRAWLERS: https://bsky.network
      LOG_ENABLED: "true"
      PDS_INVITE_REQUIRED: "false"
  