services:
  caddy:
    container_name: caddy
    image: caddy:2
    network_mode: host
    restart: unless-stopped
    volumes:
      - type: bind
        source: /pds/caddy/data
        target: /data
      - type: bind
        source: /pds/caddy/etc/caddy
        target: /etc/caddy
 
  social-app:
    image: ghcr.io/j0904/social-app:bskyweb-e26bd5f3be4dbd7005a422c0664d09240f39a9eb
    ports:
      - "8100:8100"
    environment:
      - REACT_APP_PDS_URL=https://pds.bigt.ai
      - REACT_APP_BSKY_APPVIEW_URL=https://bsky.bigt.ai


